version: '3'

services:

  solr:
    container_name: solr
    build: ./solr
    restart: always
    user: solr
    ports:
      - 8983:8983
      - 9983:9983
    #https://github.com/docker-solr/docker-solr/issues/118
    volumes:
      - /vagrant/app/solr/config/:/opt/solr/server/solr/mycores/:rw
    env_file:
      - /vagrant/app/solr/solr.env
    networks:
      - front
      - back

  prometheus:
    container_name: prometheus
    build: ./prometheus
    ports:
      - 9090:9090
    restart: always
    volumes:
      - /vagrant/app/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - front
      - middle

  grafana:
    container_name: grafana
    build: ./grafana
    ports:
      - 3000:3000
    restart: always
    volumes:
      - /vagrant/app/grafana/provisioning/:/etc/grafana/provisioning/
      - /vagrant/app/grafana/grafana.ini:/etc/grafana/grafana.ini
    command:
      - '-config=/etc/grafana/grafana.ini'
    networks:
      - front
      - middle

  indexer:
    container_name: indexer
    build: ./indexer
    depends_on:
      - solr
    ports:
      - 9000:9000
    networks:
      - back


networks:
  front:
    internal: false
  middle:
    internal: true
  back:
    internal: true